apiVersion: v1
kind: Service
metadata:
  name: collegedatabase
spec:
  selector:
    app: collegedatabase
  ports:
    - port: 8080
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegedatabase
spec:
  selector:
    matchLabels:
      app: collegedatabase
  template:
    metadata:
      labels:
        app: collegedatabase
    spec:
      containers:
        - name: collegedatabase
          image: my-college-database
          ports:
            - containerPort: 8000
          imagePullPolicy: Never