apiVersion: v1
kind: Service
metadata:
  name: collegedatabase1
spec:
  selector:
    app: collegedatabase1
  ports:
    - port: 8080
      targetPort: 8100
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegedatabase1
spec:
  selector:
    matchLabels:
      app: collegedatabase1
  template:
    metadata:
      labels:
        app: collegedatabase1
    spec:
      containers:
        - name: collegedatabase1
          image: ahteshamdocker/my-pipeline-app
          ports:
            - containerPort: 8100
          imagePullPolicy: Never
