version: 2
jobs:
  build1:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: echo "Hello world"
  build2:
    steps:
      - checkout
      - run: echo "Hello Ahtesham"  
workflows:
  build_and_test:
    jobs:
      - build1:
      - build2:
