version: 2.1

executors:
  remote_docker_executor:
    docker:
      - image: circleci/remote-docker:20.10.8

jobs:
  build_and_push:
    executor: remote_docker_executor
    steps:
      - setup_remote_docker:
          version: 20.10.8

      - checkout

      - run:
          name: Login to Docker Hub
          command: |
            echo "$realme@1234" | docker login -u "$ahteshamdocker" --password-stdin

      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t "$ahteshamdocker/my-image:latest" .
            docker push "$ahteshamdocker/my-image:latest"

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push

